### ISSUE TITLE
Middleware "VerifyCsrfToken" no longer works since TYPO3 v 10.4.10

### ISSUE THREAD

**Issue by devmes** [Lacr1ma/routes#10]
If the middleware is active, an error "CSRF token mismatch" is generated with http status 401.

Cause: https://typo3.org/security/advisory/typo3-core-sa-2020-011

**Comment by Lacr1ma** [comment]
Thanks, 2.1.0 should fix this problem. 

Also new details about the release: 

https://docs.typo3.org/p/lms/routes/2.1/en-us/ChangeLog/2.1.0.html
