### ISSUE TITLE
[FEATURE REQUEST] Allow yaml suffix for Configuration/Routes.yml

### ISSUE THREAD

**Issue by p2media** [Lacr1ma/routes#13]
It would be nice if `Configuration/Routes.yaml` would work besides `Configuration/Routes.yml`.  
To maintain compatibility I'd suggest that if both files are present, `yml` suffix would take precedence over `yaml`.

What do you think?

**Comment by Lacr1ma** [comment]
Have added this option in new release 2.1.0.

Changes: https://docs.typo3.org/p/lms/routes/2.1/en-us/ChangeLog/2.1.0.html
