### ISSUE TITLE
Request does not go past PageResolverMiddleware (404)

### ISSUE THREAD

**Issue by solakram** [Lacr1ma/routes#14]
Tag 2.0.0
TYPO3 10.4.14

i cant get my routes to work because the PageResolverMiddleware always returns a page not found.
the middleware of the extension is added after the "typo3/cms-frontend/prepare-tsfe-rendering", which will never be called since the PageResolverMiddleware will return the page not found handling and stops any further execution.

the RouteEnhancer has been added in my site config, my defined api routes are shown in the backend module (LMS: Routes).

**Comment by solakram** [comment]
Found the Problem and reported it in a new issue: #15 

also, i couldnt find the addition of 

```
routeEnhancers:
  ApplyRoutesCollection:
    type: Routes
```

in the site config in the documentation. i just stumbled upon it while checking issues on here. 
should probably be in the "Bare Minimum" section, as i guess it doesnt work without it

**Comment by Lacr1ma** [comment]
Thanks, will add this to the Bare Minimum as you mentioned.
