### ISSUE TITLE
[Improvement] Route configuration Routes.yml is not found in subfolders

### ISSUE THREAD

**Issue by Moongazer** [Lacr1ma/routes#2]
It seems the extension is not scanning subfolders like `Configuration/Yaml/` or `Configuration/Routes/` to find `Routes.yml`, and it will also not find the configuration file if the extension ends with `.yaml` instead of `.yml`.

Another thing to consider is that the file and folder name `Routes` is often used for configuration of the default TYPO3 router in other extensions. Because this extension name is `routes`, I can see some confusion or name-collitions here. Maybe `ApiRoutes.yaml` or so is a better choice to name this file?

**Comment by Lacr1ma** [comment]
From 2.1.0 you might use **Custom Paths.**

Please check if you still using the extension and might need it.
