### ISSUE TITLE
[Bug] ExtbaseRouteResolver middleware is never executed in v10

### ISSUE THREAD

**Issue by Moongazer** [Lacr1ma/routes#3]
I followed the setup of the documentation, but all test resulting in a "Page Not Found - The page did not exist or was inaccessible. Reason: The requested page does not exist" error for the given `api/demo/test` example.

From my understanding this exception is thrown early by `typo3/cms-frontend/page-resolver`, where later in the Middleware stack the `lms/routes/extbase-route-resolver` is registered. So it has no chance to hook into the routing itself (the middleware is never executed). I tried moving the extbase-route-resolver up to sit before page-resolver, but because it relies on TSFE values this was not working.

Is there any solution for it? Because in the TER this extension is marked to be functional for v10.
```
frontend
    [...]
    typo3/cms-frontend/static-route-resolver = TYPO3\CMS\Frontend\Middleware\StaticRouteResolver
    typo3/cms-frontend/page-resolver = TYPO3\CMS\Frontend\Middleware\PageResolver
    typo3/cms-frontend/preview-simulator = TYPO3\CMS\Frontend\Middleware\PreviewSimulator
    typo3/cms-frontend/page-argument-validator = TYPO3\CMS\Frontend\Middleware\PageArgumentValidator
    typo3/cms-frontend/tsfe = TYPO3\CMS\Frontend\Middleware\TypoScriptFrontendInitialization
    typo3/cms-frontend/prepare-tsfe-rendering = TYPO3\CMS\Frontend\Middleware\PrepareTypoScriptFrontendRendering
    typo3/cms-frontend/shortcut-and-mountpoint-redirect = TYPO3\CMS\Frontend\Middleware\ShortcutAndMountPointRedirect
    typo3/cms-frontend/content-length-headers = TYPO3\CMS\Frontend\Middleware\ContentLengthResponseHeader
    lms/routes/extbase-route-resolver = LMS\Routes\Middleware\ExtbaseRouteResolver
    typo3/cms-frontend/output-compression = TYPO3\CMS\Frontend\Middleware\OutputCompression
```

**System:**
TYPO3 v10.4.4 (composer)
EXT:routes v2.0.0 (tried master and v10 branch)

**Comment by Lacr1ma** [comment]
Just to be sure, you used the docs from release [2.0.0](https://docs.typo3.org/p/lms/routes/2.0/en-us/Tutorials/Minimum.html)?

And have modified your routeEnhancers like described [here](https://docs.typo3.org/p/lms/routes/2.0/en-us/Migration/Index.html)? as well as plugin in yaml has been defined and extension configuration has been updated to v10?

I presume something should not be in place in your case...
We already have ~6 projects which are on v10 and it does work.

**Comment by Moongazer** [comment]
Thank you very much for the fast reply, yes as far as I can see everything is like in your linked documents (see below). One thing just came to my mind: could the issue be related with a port-number in the domain? Because my DDEV is running on a machine with a local webserver, I set the https port to 444: `https://my-project.ddev.site:444/api/demo/test`. Given the domain in the Site-Module config, this works fine for all my other projects and extensions so far, and I never had any problems with this (just to mention this).

To track down the behavior, I put `die('stop here');exit;` as first line into the `ExtbaseRouteResolver::process()` method so see if the code reaches this point, but like I said, it seems the request never make it until here.

**Configuration/Routes.yml:** (The config is shown in the BE Routes-Module)
```
zzuser_demo-test:
  path: api/demo/test
  controller: Zenzig\ZzUser\Controller\DemoController::test
  defaults:
    plugin: DemoApi
```

**ext_localconf.php:**
```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
  'Zenzig.zz_user', // zz_user is the extension key
  'DemoApi',
  ['Demo' => 'test'],
  ['Demo' => 'test']
);
```

**DemoController.php:**
```
namespace Zenzig\ZzUser\Controller;
class DemoController extends \TYPO3\CMS\Extbase\Mvc\Controller\ActionController {
    public function testAction(): string {
        return json_encode(['ok' => true]);
    }
}
```

**Comment by Lacr1ma** [comment]
I see, looks fine to me. 

By my expectations, you might always get 404 because of Routes is not really added to the Route Collection. 

When you dump the collection result, you see any routes to be registered at all?
https://github.com/Lacr1ma/routes/blob/ff970a0dba9c2e380614bdaee3ad1505f6c71df6/Classes/Routing/RestApiEnhancer.php#L49

Should be something like that 
![routes-collection](https://user-images.githubusercontent.com/6572238/88106371-0eb96300-cbae-11ea-8cf7-a60e33a992b5.png)

In general this [is](https://github.com/Lacr1ma/routes/tree/tests-v10) the branch where it does work for TYPO3 10.4.x based on the codeception tests. Maybe you would be able to find the clue.

**Comment by Moongazer** [comment]
> By my expectations, you might always get 404 because of Routes is not really added to the Route Collection.
> When you dump the collection result, you see any routes to be registered at all?

No, it seems the "page not found" exception is thrown before this class is even called.

If I use your "tests-v10" demo project it works fine. Now I did the following to setup a completely new clean project:
```
composer create-project "typo3/cms-base-distribution:^10.4" typo3-routesapi-test
composer require lms/routes
ddev config
```
Than I copied the extension folders `routes` and `demo` from your "tests-v10" (to make sure to working with the exact same version), copied the content of `tx_demo_domain_model_entity` table, created a root-template, added routes and the demo templates, cleared the cache and opened `/api/demo/photos` with the same result: **"Reason: The requested page does not exist "**.

I can not see any difference to your "tests-v10" project, except my DDEV configuration (which is not so different from yours):
```
name: typo3-routesapi-test
type: typo3
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "81"
router_https_port: "444"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

**Comment by Lacr1ma** [comment]
Very strange issue, RestApiEnhancer should be executed in any case. Hooking into it is a core part, not the extension's as you understand. 

As you said you have added the enhancer in your site config, that's strange now... 

https://github.com/Lacr1ma/routes/blob/4f3f9f335758930dcc835c226455191072fa93c6/config/sites/root/config.yaml#L37

I have issue that you have mentioned only if I do not include that into the site config... Don't know even what to say here.

**Comment by Moongazer** [comment]
> As you said you have added the enhancer in your site config, that's strange now...
> I have issue that you have mentioned only if I do not include that into the site config... Don't know even what to say here.

WTF... just to make sure I checked the file again and the `ApplyRoutesCollection` was missing indeed! But I'm 100% sure that I put that in before! Damn... maybe it was overwritten in any of the many tryouts, folder copies and renamings and whatsoever -.- 
Anyway, you're right, its working now. Thanks a lot, I appreciate your input.
