### ISSUE TITLE
PUT and PATCH can not send data in request body

### ISSUE THREAD

**Issue by Moongazer** [Lacr1ma/routes#4]
Is there a reason why PUT and PATCH requests can not send data inside the body? Data is only accepted as query parameter, otherwise the exception "Required argument 'data' is not set for Controller->action" is thrown. This has several drawbacks like the limited length/size of the query-string, and also this miss-matches the HTTP/REST standard. Or does this behavior come from the TYPO3 Extbase controller implementation?

As example:
`GET /api/settings`
UserSettingController->show() returns the user settings for the current user (felogin)

`PUT /api/settings`
Body: {... big JSON string of user-settings...}
UserSettingController->save() updates the settings for the current user based on the session, no need to give the user-id as parameter. POST should be used if new resources are created, which is not the case here as one user has always one related setting record.

**Comment by Lacr1ma** [comment]
Sorry for delay, had too much work... 

Have updated the v10 branch for now. Try the next  approach:

1.  [Route description](https://github.com/Lacr1ma/routes/blob/442e2b68e8cb86a9d5812b5e46e28ec719d5635e/public/typo3conf/ext/demo/Configuration/Routes.yml#L142)
2. [Controller action ](https://github.com/Lacr1ma/routes/blob/442e2b68e8cb86a9d5812b5e46e28ec719d5635e/public/typo3conf/ext/demo/Classes/Controller/DemoApiController.php#L79)
3. Request
```console
curl --location --request PUT '/api/demo/photos/parse-body-param/1' --header 'Accept: application/json' --data-raw '{"foo": "bar"}'
```

Or

```console
curl --location --request PUT '/api/demo/photos/parse-body-param/1' --header 'Accept: application/json' --data-urlencode 'foo=bar'
```

Maybe still needs some improvement of the arguments binding from the Server Request, but that above should already work.

**Comment by Moongazer** [comment]
I didn't thought about `request->getArguments()`. Somehow I was expecting the values coming as action-parameter like for the POST action. Will try that out soon, thanks a lot.
