### ISSUE TITLE
Response 404 - Page not found when calling route

### ISSUE THREAD

**Issue by Schmalztopf** [Lacr1ma/routes#5]
Hello,

I try to introduce the routes extension and now get an Page not found error when trying to access the route.

My Route.yml looks as follows:

```
api-list:
   path:         api/purchases/list
   controller: Vendor\ExtKey\Controller\PurchaseAPIController::list
```

In the backend, the route definition is found and as link I get the suggestion:

`http://url/api/purchases/list`

I configured the plugin in ext_localconf.php:

```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'Vendor.ExtKey',
    'PurchaseAPI',
    [
        PurchaseAPI::class => 'list,tokens'
    ],
    [
        PurchaseAPI::class => 'list,tokens'
    ]
);
```
PurchaseAPIController looks like this:

```
<?php
namespace Vendor\ExtKey\Controller;


/**
 * PurchaseAPIController
 */
class PurchaseAPIController extends \LMS\Facade\Controller\AbstractApiController
{
    
    /**
     * action list
     * 
     * @return string
     */
    public function listAction(): string
    {
        $this->defaultViewObjectName = \TYPO3\CMS\Extbase\Mvc\View\JsonView::class;
        return json_encode(
            ['ok' => true]
        );
    }

       /**
        * {@inheritdoc}
        */
       protected function getRootName(): string
       {
           return 'subscriptions';
       }

       /**
         * {@inheritdoc}
         */
        protected function getResourceRepository(): \TYPO3\CMS\Extbase\Persistence\RepositoryInterface
        {
            return \Vendor\ExtKey\Domain\Repository\PurchaseRepository::make();
        }
 }
```

I also included the static template in the Root of the page.

What might be missing that prevents calling the controller listAction?

Best regards
Thomas Gramer

**Comment by Lacr1ma** [comment]
Hello, 

Did you update the site configuration ? 

https://github.com/Lacr1ma/routes/blob/4f3f9f335758930dcc835c226455191072fa93c6/config/sites/root/config.yaml#L37

**Comment by Schmalztopf** [comment]
No I didn't. That was one step closer to the solution. Indeed I thought, I could use any path inside routes, but it seems, that it has to be the "enhancement" of an existing page url. In my example a page called "api". Can you confirm that? After creating such a page the routing worked. Thanks a lot and also for the nice example project.
